<?xml version="1.0" encoding="UTF-8"?>
<!-- <!DOCTYPE biblioteca SYSTEM "../dtd/biblioteca.dtd"> -->
<!DOCTYPE biblioteca [
    <!ELEMENT biblioteca (libros|revistas|periodicos)*>

  <!-- Definicion etiqueta libro -->

  <!ELEMENT libros (libro*)>
  <!ELEMENT libro (titulo,capitulo+,indice,sinopsis+)>
  <!ATTLIST libro
                id CDATA #REQUIRED
                tipo_clase CDATA #IMPLIED
                paginas CDATA #IMPLIED
  >
  <!ELEMENT titulo (#PCDATA)>
  <!ELEMENT capitulo (titulo, contenido)>
  <!ATTLIST capitulo paginas CDATA #IMPLIED>
  <!ELEMENT contenido (#PCDATA)>
  <!ATTLIST contenido enlace CDATA #IMPLIED>
  
  <!ELEMENT sinopsis (#PCDATA)>
  
    <!-- Definicion etiqueta revista -->

  <!ELEMENT revistas (revista*)>
  <!ELEMENT revista (titulo, numero, indice, seccion_revista+)>
  <!ATTLIST revista 
             id CDATA #REQUIRED
             tipo_clase CDATA #IMPLIED
			 paginas CDATA #IMPLIED
  >
  <!ELEMENT numero (#PCDATA)>
  <!ELEMENT seccion_revista (contenido)>
  <!ATTLIST seccion_revista paginas CDATA #IMPLIED>

  <!-- Definicion etiqueta periodico -->

  <!ELEMENT periodicos (periodico*)>
  <!ELEMENT periodico (indice, seccion_periodico+)>
  <!ATTLIST periodico id CDATA #REQUIRED>
  <!ATTLIST periodico tipo_clase CDATA #IMPLIED>
  <!ATTLIST periodico fecha_publicacion CDATA #REQUIRED>
  <!ATTLIST seccion_periodico tipo CDATA #IMPLIED>
  <!ELEMENT seccion_periodico (articulo*, contenido_periodico)>
  <!ELEMENT articulo (#PCDATA)>
  <!ATTLIST articulo autor CDATA #IMPLIED>
  <!ELEMENT contenido_periodico (#PCDATA)>
  <!ATTLIST contenido_periodico referencia CDATA #IMPLIED>


  <!-- Definición de comunes -->
  <!ELEMENT indice (encabezado, apartado+)>
  <!ELEMENT encabezado (#PCDATA)>
  <!ELEMENT apartado (#PCDATA)>
  <!ATTLIST apartado titulo CDATA #REQUIRED>
  <!ATTLIST apartado pagina CDATA #REQUIRED>
]>

<biblioteca>
     <!-- Estructura de un <libro> clasificacion = "novela | infantil | didáctico"-->
   <libros>
        <libro id="L0001" tipo_clase ="novela" paginas="10">
            <titulo>Titulo del libro</titulo>
            <capitulo paginas="1">
                <titulo>Titulo del capitulo</titulo>
                <contenido enlace="https://www.google.es/">Lorem ipsum</contenido>
            </capitulo>
            <capitulo paginas="7">
                <titulo>Titulo del capitulo</titulo>
                <contenido enlace="https://www.google.es/">Lorem ipsum</contenido>
            </capitulo>
            <indice>
                <encabezado>Encabezado</encabezado>
                <apartado titulo="Título apartado 1" pagina="2"/>
                <apartado titulo="Título apartado 2" pagina="4"/>
            </indice>
            <sinopsis>Resumen del libro</sinopsis>
        </libro>
        <libro id="L0002" tipo_clase ="didáctico">
            <titulo>Titulo del libro</titulo>
            <capitulo paginas="1">
                <titulo>Titulo del capitulo</titulo>
                <contenido enlace="https://www.google.es/">Lorem ipsum</contenido>
            </capitulo>
            <capitulo paginas="7">
                <titulo>Titulo del capitulo</titulo>
                <contenido enlace="https://www.google.es/">Lorem ipsum</contenido>
            </capitulo>
            <indice>
                <encabezado>Encabezado</encabezado>
                <apartado titulo="Título apartado 1" pagina="2"/>
                <apartado titulo="Título apartado 2" pagina="4"/>
            </indice>
            <sinopsis>Resumen del libro</sinopsis>
        </libro>
        <libro id="L0003" tipo_clase ="infantil">
            <titulo>Titulo del libro</titulo>
            <capitulo paginas="1">
                <titulo>Titulo del capitulo</titulo>
                <contenido enlace="https://www.google.es/">Lorem ipsum</contenido>
            </capitulo>
            <capitulo paginas="7">
                <titulo>Titulo del capitulo</titulo>
                <contenido enlace="https://www.google.es/">Lorem ipsum</contenido>
            </capitulo>
            <indice>
                <encabezado>Encabezado</encabezado>
                <apartado titulo="Título apartado 1" pagina="2"/>
            </indice>
            <sinopsis>Resumen del libro</sinopsis>
        </libro>
         <libro id="L0004">
            <titulo>Titulo del libro</titulo>
            <capitulo>
                <titulo>Titulo del capitulo</titulo>
                <contenido>Lorem ipsum</contenido>
            </capitulo>
            <capitulo>
                <titulo>Titulo del capitulo</titulo>
                <contenido>Lorem ipsum</contenido>
            </capitulo>
            <indice>
                <encabezado>Encabezado</encabezado>
                <apartado titulo="Título apartado 1" pagina="2"/>
            </indice>
            <sinopsis>Resumen del libro</sinopsis>
        </libro>        
   </libros>

    <!-- Estructura de una <revista> clasificacion = "informática | corazón | coches | investigación | otras" -->
    <revistas>
        <revista id="R0001" tipo_clase="otras" paginas="120">
            <titulo>Título de la revista</titulo>
            <numero>1</numero>
            <indice>
                <encabezado>Encabezado</encabezado>
                <apartado titulo="La historia de Edix " pagina="1" />
                <apartado titulo="La historia de Edix " pagina="62" />
            </indice>
            <seccion_revista paginas="1">
                <contenido enlace="https://www.google.es/">Contenido de la revista</contenido>
            </seccion_revista>
        </revista>
        <revista id="R0002" tipo_clase="investigación" paginas="1">
            <titulo>Título de la revista</titulo>
            <numero>1</numero>
            <indice>
                <encabezado>Encabezado</encabezado>
                <apartado titulo="La historia de Edix " pagina="1" />
                <apartado titulo="La historia de Edix " pagina="3" />
            </indice>
            <seccion_revista paginas="1">
                <contenido enlace="https://www.google.es/">Contenido de la revista</contenido>
            </seccion_revista>
        </revista>
        <revista id="R0003" tipo_clase="informática" paginas="1">
            <titulo>Título de la revista</titulo>
            <numero>1</numero>
            <indice>
                <encabezado>Encabezado</encabezado>
                <apartado titulo="La historia de Edix " pagina="1" />
                <apartado titulo="La historia de Edix " pagina="3" />
            </indice>
            <seccion_revista paginas="1">
                <contenido enlace="https://www.google.es/">Contenido de la revista</contenido>
            </seccion_revista>
        </revista>
        <revista id="R0004" tipo_clase="corazón" paginas="1">
            <titulo>Título de la revista</titulo>
            <numero>1</numero>
            <indice>
                <encabezado>Encabezado</encabezado>
                <apartado titulo="La historia de Edix " pagina="1" />
                <apartado titulo="La historia de Edix " pagina="3" />
            </indice>
            <seccion_revista paginas="1">
                <contenido enlace="https://www.google.es/">Contenido de la revista</contenido>
            </seccion_revista>
        </revista>
        <revista id="R0005" tipo_clase="coches" paginas="1">
            <titulo>Título de la revista</titulo>
            <numero>1</numero>
            <indice>
                <encabezado>Encabezado</encabezado>
                <apartado titulo="La historia de Edix " pagina="1" />
                <apartado titulo="La historia de Edix " pagina="3" />
            </indice>
            <seccion_revista paginas="1">
                <contenido enlace="https://www.google.es/">Contenido de la revista</contenido>
            </seccion_revista>
        </revista>
        <revista id="R0006">
            <titulo>Título de la revista</titulo>
            <numero>1</numero>
            <indice>
                <encabezado>Encabezado</encabezado>
                <apartado titulo="La historia de Edix " pagina="1" />
            </indice>
            <seccion_revista>
                <contenido>Contenido de la revista</contenido>
            </seccion_revista>
        </revista>
    </revistas>

    <!-- Estructura de un <periodico> clasificacion = "nacional | internaciona"-->
    <periodicos>
        <periodico id="P0001" tipo_clase="nacional" fecha_publicacion="1997-10-29">
            <indice>                            
                <encabezado>Encabezado</encabezado>
                <apartado titulo="La historia de Edix " pagina="1" />
            </indice>
            <seccion_periodico tipo="opinión"> <!-- tipo="economía | opinión | deportes | nacional |internacional" -->
                <articulo autor="Pedro"></articulo>
                <contenido_periodico referencia="https://www.google.es/">Informacion</contenido_periodico>
            </seccion_periodico>            
        </periodico>
        <periodico id="P0002" tipo_clase="internacional" fecha_publicacion="1997-10-29">
            <indice>                            
                <encabezado>Encabezado</encabezado>
                <apartado titulo="La historia de Edix " pagina="1" />
            </indice>
            <seccion_periodico tipo="deportes"> <!-- tipo="economía | opinión | deportes | nacional |internacional" -->
                <articulo autor="Juán"></articulo>
                <contenido_periodico referencia="https://www.google.es/">Informacion</contenido_periodico>
            </seccion_periodico>            
        </periodico>
         <periodico id="P0003" fecha_publicacion="1997-10-29">
            <indice>                            
                <encabezado>Encabezado</encabezado>
                <apartado titulo="La historia de Edix " pagina="1" />
            </indice>
            <seccion_periodico > <!-- tipo="economía | opinión | deportes | nacional |internacional" -->
                <articulo autor="Juán"></articulo>
                <contenido_periodico referencia="https://www.google.es/">Informacion</contenido_periodico>
            </seccion_periodico>            
        </periodico>
    </periodicos></biblioteca>
